2021-10-18 23:52:03,862 INFO apscheduler.scheduler : Scheduler started
2021-10-18 23:52:04,002 INFO apscheduler.scheduler : Added job "create_app.<locals>.scarp_users_history" to job store "default"
2021-10-18 23:52:04,014 WARNING werkzeug :  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-10-18 23:52:04,014 INFO werkzeug :  * Running on http://192.168.1.65:5000/ (Press CTRL+C to quit)
2021-10-18 23:52:04,015 INFO werkzeug :  * Restarting with stat
2021-10-18 23:52:11,539 INFO apscheduler.scheduler : Scheduler started
2021-10-18 23:52:11,665 INFO apscheduler.scheduler : Added job "create_app.<locals>.scarp_users_history" to job store "default"
2021-10-18 23:52:11,677 WARNING werkzeug :  * Debugger is active!
2021-10-18 23:52:11,697 INFO werkzeug :  * Debugger PIN: 142-798-951
2021-10-18 23:52:27,777 INFO werkzeug : 192.168.1.65 - - [18/Oct/2021 23:52:27] "GET / HTTP/1.1" 200 -
2021-10-18 23:52:27,939 INFO werkzeug : 192.168.1.65 - - [18/Oct/2021 23:52:27] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
2021-10-18 23:52:27,954 INFO werkzeug : 192.168.1.65 - - [18/Oct/2021 23:52:27] "[36mGET /static/logo2.svg HTTP/1.1[0m" 304 -
2021-10-19 00:00:00,099 INFO apscheduler.executors.default : Running job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-10-19 00:00:00 MSK)" (scheduled at 2021-10-19 00:00:00+03:00)
2021-10-19 00:00:00,107 INFO apscheduler.executors.default : Running job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-10-19 00:00:00 MSK)" (scheduled at 2021-10-19 00:00:00+03:00)
2021-10-19 00:00:05,116 INFO apscheduler.executors.default : Job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-10-19 00:30:00 MSK)" executed successfully
2021-10-19 00:00:05,131 INFO apscheduler.executors.default : Job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-10-19 00:30:00 MSK)" executed successfully
2021-10-20 22:45:20,433 INFO werkzeug :  * Detected change in '/Users/roma/Desktop/moodifyspotify/text_emotions_job.py', reloading
2021-10-20 22:45:22,521 INFO werkzeug :  * Restarting with stat
2021-10-20 22:45:35,307 INFO apscheduler.scheduler : Scheduler started
2021-10-20 22:45:35,446 INFO apscheduler.scheduler : Added job "create_app.<locals>.scarp_users_history" to job store "default"
2021-10-20 22:45:35,454 WARNING werkzeug :  * Debugger is active!
2021-10-20 22:45:35,474 INFO werkzeug :  * Debugger PIN: 142-798-951
2021-10-20 22:50:01,227 INFO apscheduler.scheduler : Scheduler started
2021-10-20 22:50:01,356 INFO apscheduler.scheduler : Added job "create_app.<locals>.scarp_users_history" to job store "default"
2021-10-20 22:50:01,365 WARNING werkzeug :  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-10-20 22:50:01,365 INFO werkzeug :  * Running on http://192.168.1.65:5000/ (Press CTRL+C to quit)
2021-10-20 22:50:01,366 INFO werkzeug :  * Restarting with stat
2021-10-20 22:50:09,914 INFO apscheduler.scheduler : Scheduler started
2021-10-20 22:50:10,083 INFO apscheduler.scheduler : Added job "create_app.<locals>.scarp_users_history" to job store "default"
2021-10-20 22:50:10,106 WARNING werkzeug :  * Debugger is active!
2021-10-20 22:50:10,126 INFO werkzeug :  * Debugger PIN: 142-798-951
2021-10-20 22:51:09,774 INFO apscheduler.scheduler : Scheduler started
2021-10-20 22:51:09,938 INFO apscheduler.scheduler : Added job "create_app.<locals>.scarp_users_history" to job store "default"
2021-10-20 22:51:09,953 WARNING werkzeug :  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-10-20 22:51:09,954 INFO werkzeug :  * Running on http://192.168.1.65:5000/ (Press CTRL+C to quit)
2021-10-20 22:51:09,955 INFO werkzeug :  * Restarting with stat
2021-10-20 22:51:18,908 INFO apscheduler.scheduler : Scheduler started
2021-10-20 22:51:19,041 INFO apscheduler.scheduler : Added job "create_app.<locals>.scarp_users_history" to job store "default"
2021-10-20 22:51:19,050 WARNING werkzeug :  * Debugger is active!
2021-10-20 22:51:19,063 INFO werkzeug :  * Debugger PIN: 142-798-951
2021-10-20 22:51:30,289 INFO werkzeug : 192.168.1.65 - - [20/Oct/2021 22:51:30] "GET / HTTP/1.1" 200 -
2021-10-20 22:51:30,631 INFO werkzeug : 192.168.1.65 - - [20/Oct/2021 22:51:30] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
2021-10-20 22:51:30,658 INFO werkzeug : 192.168.1.65 - - [20/Oct/2021 22:51:30] "[36mGET /static/logo2.svg HTTP/1.1[0m" 304 -
2021-10-20 22:51:59,229 INFO apscheduler.scheduler : Scheduler started
2021-10-20 22:51:59,423 INFO apscheduler.scheduler : Added job "create_app.<locals>.scarp_users_history" to job store "default"
2021-10-20 22:51:59,435 WARNING werkzeug :  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-10-20 22:51:59,435 INFO werkzeug :  * Running on http://192.168.1.65:5000/ (Press CTRL+C to quit)
2021-10-20 22:51:59,438 INFO werkzeug :  * Restarting with stat
2021-10-20 22:52:07,882 INFO apscheduler.scheduler : Scheduler started
2021-10-20 22:52:08,010 INFO apscheduler.scheduler : Added job "create_app.<locals>.scarp_users_history" to job store "default"
2021-10-20 22:52:08,020 WARNING werkzeug :  * Debugger is active!
2021-10-20 22:52:08,036 INFO werkzeug :  * Debugger PIN: 142-798-951
2021-10-20 22:53:18,195 INFO werkzeug : 192.168.1.65 - - [20/Oct/2021 22:53:18] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
2021-10-20 22:54:09,201 INFO werkzeug : 192.168.1.65 - - [20/Oct/2021 22:54:09] "GET / HTTP/1.1" 200 -
2021-10-20 22:54:09,383 INFO werkzeug : 192.168.1.65 - - [20/Oct/2021 22:54:09] "GET /static/style.css HTTP/1.1" 200 -
2021-10-20 22:54:09,394 INFO werkzeug : 192.168.1.65 - - [20/Oct/2021 22:54:09] "[36mGET /static/logo2.svg HTTP/1.1[0m" 304 -
2021-10-20 22:54:22,853 INFO werkzeug : 192.168.1.65 - - [20/Oct/2021 22:54:22] "GET / HTTP/1.1" 200 -
2021-10-20 22:54:22,950 INFO werkzeug : 192.168.1.65 - - [20/Oct/2021 22:54:22] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
2021-10-20 22:54:23,041 INFO werkzeug : 192.168.1.65 - - [20/Oct/2021 22:54:23] "[36mGET /static/logo2.svg HTTP/1.1[0m" 304 -
2021-10-20 23:00:00,016 INFO apscheduler.executors.default : Running job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-10-20 23:00:00 MSK)" (scheduled at 2021-10-20 23:00:00+03:00)
2021-10-20 23:00:00,018 INFO apscheduler.executors.default : Running job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-10-20 23:00:00 MSK)" (scheduled at 2021-10-20 23:00:00+03:00)
2021-10-20 23:00:02,404 INFO apscheduler.executors.default : Job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-10-20 23:30:00 MSK)" executed successfully
2021-10-20 23:00:03,278 INFO apscheduler.executors.default : Job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-10-20 23:30:00 MSK)" executed successfully
2021-10-20 23:08:43,388 INFO werkzeug : 192.168.1.65 - - [20/Oct/2021 23:08:43] "GET / HTTP/1.1" 200 -
2021-10-20 23:08:43,502 INFO werkzeug : 192.168.1.65 - - [20/Oct/2021 23:08:43] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
2021-10-20 23:08:43,600 INFO werkzeug : 192.168.1.65 - - [20/Oct/2021 23:08:43] "[36mGET /static/logo2.svg HTTP/1.1[0m" 304 -
2021-10-20 23:17:26,203 INFO werkzeug : 192.168.1.65 - - [20/Oct/2021 23:17:26] "GET / HTTP/1.1" 200 -
2021-10-20 23:17:26,438 INFO werkzeug : 192.168.1.65 - - [20/Oct/2021 23:17:26] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
2021-10-20 23:17:26,668 INFO werkzeug : 192.168.1.65 - - [20/Oct/2021 23:17:26] "[36mGET /static/logo2.svg HTTP/1.1[0m" 304 -
2021-10-20 23:17:56,867 INFO werkzeug : 192.168.1.65 - - [20/Oct/2021 23:17:56] "GET / HTTP/1.1" 200 -
2021-10-20 23:17:56,946 INFO werkzeug : 192.168.1.65 - - [20/Oct/2021 23:17:56] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
2021-10-20 23:17:57,000 INFO werkzeug : 192.168.1.65 - - [20/Oct/2021 23:17:57] "[36mGET /static/logo2.svg HTTP/1.1[0m" 304 -
2021-10-20 23:19:03,873 INFO werkzeug :  * Detected change in '/Users/roma/Desktop/moodifyspotify/flask_app.py', reloading
2021-10-20 23:19:09,619 INFO werkzeug :  * Restarting with stat
2021-10-20 23:19:27,910 INFO apscheduler.scheduler : Scheduler started
2021-10-20 23:19:28,024 INFO apscheduler.scheduler : Added job "create_app.<locals>.scarp_users_history" to job store "default"
2021-10-20 23:19:28,034 WARNING werkzeug :  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-10-20 23:19:28,034 INFO werkzeug :  * Running on http://192.168.1.65:5000/ (Press CTRL+C to quit)
2021-10-20 23:19:28,037 INFO werkzeug :  * Restarting with stat
2021-10-20 23:19:35,857 INFO apscheduler.scheduler : Scheduler started
2021-10-20 23:19:35,961 INFO apscheduler.scheduler : Added job "create_app.<locals>.scarp_users_history" to job store "default"
2021-10-20 23:19:35,969 WARNING werkzeug :  * Debugger is active!
2021-10-20 23:19:35,989 INFO werkzeug :  * Debugger PIN: 142-798-951
2021-10-20 23:19:44,855 INFO werkzeug : 192.168.1.65 - - [20/Oct/2021 23:19:44] "GET / HTTP/1.1" 200 -
2021-10-20 23:19:44,986 INFO werkzeug : 192.168.1.65 - - [20/Oct/2021 23:19:44] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
2021-10-20 23:19:45,225 INFO werkzeug : 192.168.1.65 - - [20/Oct/2021 23:19:45] "[36mGET /static/logo2.svg HTTP/1.1[0m" 304 -
2021-10-20 23:19:49,267 INFO werkzeug : 192.168.1.65 - - [20/Oct/2021 23:19:49] "GET / HTTP/1.1" 200 -
2021-10-20 23:19:49,351 INFO werkzeug : 192.168.1.65 - - [20/Oct/2021 23:19:49] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
2021-10-20 23:19:49,352 INFO werkzeug : 192.168.1.65 - - [20/Oct/2021 23:19:49] "[36mGET /static/logo2.svg HTTP/1.1[0m" 304 -
2021-10-20 23:19:56,273 INFO werkzeug : 192.168.1.65 - - [20/Oct/2021 23:19:56] "[32mGET /spotify_auth?code=AQCSvNVioTgIQD7I8_x69xPwcu2qvh1QGNiOB5Rm87sMZNGxx2FckMcJypzidMVdHCNMcQO8hkCn61KYFxW6JHY8Jku0OBjK5Ld5120fInWeMqhONh0UyzWQWqzmiGkFdWDizVacBglFaV0eBEBU2YIEk69CGvhmfdrlTkoH-5J-TWCFyEfN2zNqDcQg5oX9NJupo_FyXETZdLo9HBZBJF2-zjIc4PYGWDI0K7uYScdSVZd28vOPDkpTU3ak7B-AGq927xpglyP9LLVfXzdB5ikIe8qcivL9oiBjjq14ZVyy9yQXSinIaajxHkaMwEweRDvi-7bdKis HTTP/1.1[0m" 302 -
2021-10-20 23:19:58,398 INFO werkzeug : 192.168.1.65 - - [20/Oct/2021 23:19:58] "GET / HTTP/1.1" 200 -
2021-10-20 23:19:58,499 INFO werkzeug : 192.168.1.65 - - [20/Oct/2021 23:19:58] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
2021-10-20 23:19:58,593 INFO werkzeug : 192.168.1.65 - - [20/Oct/2021 23:19:58] "[36mGET /static/logo2.svg HTTP/1.1[0m" 304 -
2021-10-20 23:20:37,321 INFO werkzeug : 192.168.1.65 - - [20/Oct/2021 23:20:37] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
2021-10-20 23:21:08,481 INFO werkzeug : 192.168.1.65 - - [20/Oct/2021 23:21:08] "GET / HTTP/1.1" 200 -
2021-10-20 23:21:08,580 INFO werkzeug : 192.168.1.65 - - [20/Oct/2021 23:21:08] "GET /static/style.css HTTP/1.1" 200 -
2021-10-20 23:21:09,430 INFO werkzeug : 192.168.1.65 - - [20/Oct/2021 23:21:09] "[36mGET /static/logo2.svg HTTP/1.1[0m" 304 -
2021-10-20 23:22:17,711 INFO werkzeug : 192.168.1.65 - - [20/Oct/2021 23:22:17] "GET / HTTP/1.1" 200 -
2021-10-20 23:22:17,853 INFO werkzeug : 192.168.1.65 - - [20/Oct/2021 23:22:17] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
2021-10-20 23:22:18,049 INFO werkzeug : 192.168.1.65 - - [20/Oct/2021 23:22:18] "[36mGET /static/logo2.svg HTTP/1.1[0m" 304 -
2021-10-20 23:23:31,353 INFO werkzeug : 192.168.1.65 - - [20/Oct/2021 23:23:31] "GET / HTTP/1.1" 200 -
2021-10-20 23:23:31,460 INFO werkzeug : 192.168.1.65 - - [20/Oct/2021 23:23:31] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
2021-10-20 23:23:32,337 INFO werkzeug : 192.168.1.65 - - [20/Oct/2021 23:23:32] "[36mGET /static/logo2.svg HTTP/1.1[0m" 304 -
2021-10-20 23:30:00,198 INFO apscheduler.executors.default : Running job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-10-20 23:30:00 MSK)" (scheduled at 2021-10-20 23:30:00+03:00)
2021-10-20 23:30:00,199 INFO apscheduler.executors.default : Running job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-10-20 23:30:00 MSK)" (scheduled at 2021-10-20 23:30:00+03:00)
2021-10-20 23:30:02,992 INFO apscheduler.executors.default : Job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-10-21 00:00:00 MSK)" executed successfully
2021-10-20 23:30:03,459 INFO apscheduler.executors.default : Job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-10-21 00:00:00 MSK)" executed successfully
2021-10-21 00:00:00,104 INFO apscheduler.executors.default : Running job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-10-21 00:30:00 MSK)" (scheduled at 2021-10-21 00:00:00+03:00)
2021-10-21 00:00:00,114 INFO apscheduler.executors.default : Running job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-10-21 00:30:00 MSK)" (scheduled at 2021-10-21 00:00:00+03:00)
2021-10-21 00:00:02,239 INFO apscheduler.executors.default : Job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-10-21 00:30:00 MSK)" executed successfully
2021-10-21 00:00:02,311 INFO apscheduler.executors.default : Job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-10-21 00:30:00 MSK)" executed successfully
2021-10-21 00:30:00,032 INFO apscheduler.executors.default : Running job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-10-21 01:00:00 MSK)" (scheduled at 2021-10-21 00:30:00+03:00)
2021-10-21 00:30:00,032 INFO apscheduler.executors.default : Running job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-10-21 01:00:00 MSK)" (scheduled at 2021-10-21 00:30:00+03:00)
2021-10-21 00:30:00,432 ERROR apscheduler.executors.default : Job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-10-21 01:00:00 MSK)" raised an exception
Traceback (most recent call last):
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/roma/Desktop/moodifyspotify/flask_app.py", line 396, in scarp_users_history
    tracks_history = sp_user_clt.get_user_recent_tracks()
  File "/Users/roma/Desktop/moodifyspotify/spotify_client.py", line 124, in get_user_recent_tracks
    for lu in resp['items']:
KeyError: 'items'
2021-10-21 00:30:00,540 ERROR apscheduler.executors.default : Job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-10-21 01:00:00 MSK)" raised an exception
Traceback (most recent call last):
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/roma/Desktop/moodifyspotify/flask_app.py", line 396, in scarp_users_history
    tracks_history = sp_user_clt.get_user_recent_tracks()
  File "/Users/roma/Desktop/moodifyspotify/spotify_client.py", line 124, in get_user_recent_tracks
    for lu in resp['items']:
KeyError: 'items'
2021-10-27 21:54:56,419 WARNING apscheduler.executors.default : Run time of job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-10-27 22:00:00 MSK)" was missed by 0:24:56.417455
2021-10-27 21:54:56,419 WARNING apscheduler.executors.default : Run time of job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-10-27 22:00:00 MSK)" was missed by 0:24:56.415277
2021-10-27 22:00:01,262 WARNING apscheduler.executors.default : Run time of job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-10-27 22:30:00 MSK)" was missed by 0:00:01.262429
2021-10-27 22:00:01,272 WARNING apscheduler.executors.default : Run time of job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-10-27 22:30:00 MSK)" was missed by 0:00:01.272336
2021-10-28 12:51:19,369 WARNING apscheduler.executors.default : Run time of job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-10-28 13:00:00 MSK)" was missed by 0:21:19.368129
2021-10-28 12:51:19,371 WARNING apscheduler.executors.default : Run time of job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-10-28 13:00:00 MSK)" was missed by 0:21:19.370450
2021-10-28 13:00:00,036 INFO apscheduler.executors.default : Running job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-10-28 13:30:00 MSK)" (scheduled at 2021-10-28 13:00:00+03:00)
2021-10-28 13:00:00,040 INFO apscheduler.executors.default : Running job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-10-28 13:30:00 MSK)" (scheduled at 2021-10-28 13:00:00+03:00)
2021-10-28 13:00:30,127 ERROR apscheduler.executors.default : Job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-10-28 13:30:00 MSK)" raised an exception
Traceback (most recent call last):
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/roma/Desktop/moodifyspotify/flask_app.py", line 391, in scarp_users_history
    users = mongo_conn.get_all_users()
  File "/Users/roma/Desktop/moodifyspotify/mongo_connector.py", line 46, in get_all_users
    for u in self.dbs.users.find():
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1130, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1935, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1883, in __start_session
    server_session = self._get_server_session()
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1921, in _get_server_session
    return self._topology.get_server_session()
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/topology.py", line 520, in get_server_session
    session_timeout = self._check_session_support()
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/topology.py", line 504, in _check_session_support
    self._select_servers_loop(
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/topology.py", line 218, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: rc1a-zptn64g6pn8ylwgh.mdb.yandexcloud.net:27018: [Errno 8] nodename nor servname provided, or not known, Timeout: 30s, Topology Description: <TopologyDescription id: 617079d7ccabbe952692dff8, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('rc1a-zptn64g6pn8ylwgh.mdb.yandexcloud.net', 27018) server_type: Unknown, rtt: None, error=AutoReconnect('rc1a-zptn64g6pn8ylwgh.mdb.yandexcloud.net:27018: [Errno 8] nodename nor servname provided, or not known')>]>
2021-10-28 13:00:30,458 ERROR apscheduler.executors.default : Job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-10-28 13:30:00 MSK)" raised an exception
Traceback (most recent call last):
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/roma/Desktop/moodifyspotify/flask_app.py", line 391, in scarp_users_history
    users = mongo_conn.get_all_users()
  File "/Users/roma/Desktop/moodifyspotify/mongo_connector.py", line 46, in get_all_users
    for u in self.dbs.users.find():
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1130, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1935, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1883, in __start_session
    server_session = self._get_server_session()
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1921, in _get_server_session
    return self._topology.get_server_session()
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/topology.py", line 520, in get_server_session
    session_timeout = self._check_session_support()
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/topology.py", line 504, in _check_session_support
    self._select_servers_loop(
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/topology.py", line 218, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: rc1a-zptn64g6pn8ylwgh.mdb.yandexcloud.net:27018: [Errno 8] nodename nor servname provided, or not known, Timeout: 30s, Topology Description: <TopologyDescription id: 617079cfd660d857bd50c176, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('rc1a-zptn64g6pn8ylwgh.mdb.yandexcloud.net', 27018) server_type: Unknown, rtt: None, error=AutoReconnect('rc1a-zptn64g6pn8ylwgh.mdb.yandexcloud.net:27018: [Errno 8] nodename nor servname provided, or not known')>]>
2021-10-29 17:16:18,542 WARNING apscheduler.executors.default : Run time of job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-10-29 13:30:00 MSK)" was missed by 0:16:18.533497
2021-10-29 17:16:18,561 WARNING apscheduler.executors.default : Run time of job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-10-29 13:30:00 MSK)" was missed by 0:16:18.550037
2021-11-01 02:43:40,549 WARNING apscheduler.executors.default : Run time of job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-10-31 23:00:00 MSK)" was missed by 0:13:40.548285
2021-11-01 02:43:40,549 WARNING apscheduler.executors.default : Run time of job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-10-31 23:00:00 MSK)" was missed by 0:13:40.548062
2021-11-01 05:13:35,417 WARNING apscheduler.executors.default : Run time of job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-01 01:30:00 MSK)" was missed by 0:13:35.416410
2021-11-01 05:13:35,417 WARNING apscheduler.executors.default : Run time of job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-10-31 23:00:00 MSK)" was missed by 0:13:35.416295
2021-11-02 01:07:55,801 WARNING apscheduler.executors.default : Run time of job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-01 21:30:00 MSK)" was missed by 0:07:55.800294
2021-11-02 01:07:55,801 WARNING apscheduler.executors.default : Run time of job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-01 21:30:00 MSK)" was missed by 0:07:55.800446
2021-11-02 01:30:00,055 INFO apscheduler.executors.default : Running job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-01 22:00:00 MSK)" (scheduled at 2021-11-01 21:30:00+03:00)
2021-11-02 01:30:00,062 INFO apscheduler.executors.default : Running job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-01 22:00:00 MSK)" (scheduled at 2021-11-01 21:30:00+03:00)
2021-11-02 01:30:30,156 ERROR apscheduler.executors.default : Job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-01 22:00:00 MSK)" raised an exception
Traceback (most recent call last):
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/roma/Desktop/moodifyspotify/flask_app.py", line 391, in scarp_users_history
    users = mongo_conn.get_all_users()
  File "/Users/roma/Desktop/moodifyspotify/mongo_connector.py", line 46, in get_all_users
    for u in self.dbs.users.find():
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1130, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1935, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1883, in __start_session
    server_session = self._get_server_session()
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1921, in _get_server_session
    return self._topology.get_server_session()
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/topology.py", line 520, in get_server_session
    session_timeout = self._check_session_support()
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/topology.py", line 504, in _check_session_support
    self._select_servers_loop(
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/topology.py", line 218, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: rc1a-zptn64g6pn8ylwgh.mdb.yandexcloud.net:27018: [Errno 61] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 617079cfd660d857bd50c176, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('rc1a-zptn64g6pn8ylwgh.mdb.yandexcloud.net', 27018) server_type: Unknown, rtt: None, error=AutoReconnect('rc1a-zptn64g6pn8ylwgh.mdb.yandexcloud.net:27018: [Errno 61] Connection refused')>]>
2021-11-02 01:30:30,156 ERROR apscheduler.executors.default : Job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-01 22:00:00 MSK)" raised an exception
Traceback (most recent call last):
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/roma/Desktop/moodifyspotify/flask_app.py", line 391, in scarp_users_history
    users = mongo_conn.get_all_users()
  File "/Users/roma/Desktop/moodifyspotify/mongo_connector.py", line 46, in get_all_users
    for u in self.dbs.users.find():
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1130, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1935, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1883, in __start_session
    server_session = self._get_server_session()
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1921, in _get_server_session
    return self._topology.get_server_session()
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/topology.py", line 520, in get_server_session
    session_timeout = self._check_session_support()
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/topology.py", line 504, in _check_session_support
    self._select_servers_loop(
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/topology.py", line 218, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: rc1a-zptn64g6pn8ylwgh.mdb.yandexcloud.net:27018: [Errno 61] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 617079d7ccabbe952692dff8, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('rc1a-zptn64g6pn8ylwgh.mdb.yandexcloud.net', 27018) server_type: Unknown, rtt: None, error=AutoReconnect('rc1a-zptn64g6pn8ylwgh.mdb.yandexcloud.net:27018: [Errno 61] Connection refused')>]>
2021-11-02 02:00:00,063 INFO apscheduler.executors.default : Running job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-01 22:30:00 MSK)" (scheduled at 2021-11-01 22:00:00+03:00)
2021-11-02 02:00:00,063 INFO apscheduler.executors.default : Running job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-01 22:30:00 MSK)" (scheduled at 2021-11-01 22:00:00+03:00)
2021-11-02 02:00:30,136 ERROR apscheduler.executors.default : Job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-01 22:30:00 MSK)" raised an exception
Traceback (most recent call last):
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/roma/Desktop/moodifyspotify/flask_app.py", line 391, in scarp_users_history
    users = mongo_conn.get_all_users()
  File "/Users/roma/Desktop/moodifyspotify/mongo_connector.py", line 46, in get_all_users
    for u in self.dbs.users.find():
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1130, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1935, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1883, in __start_session
    server_session = self._get_server_session()
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1921, in _get_server_session
    return self._topology.get_server_session()
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/topology.py", line 520, in get_server_session
    session_timeout = self._check_session_support()
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/topology.py", line 504, in _check_session_support
    self._select_servers_loop(
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/topology.py", line 218, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: rc1a-zptn64g6pn8ylwgh.mdb.yandexcloud.net:27018: [Errno 61] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 617079d7ccabbe952692dff8, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('rc1a-zptn64g6pn8ylwgh.mdb.yandexcloud.net', 27018) server_type: Unknown, rtt: None, error=AutoReconnect('rc1a-zptn64g6pn8ylwgh.mdb.yandexcloud.net:27018: [Errno 61] Connection refused')>]>
2021-11-02 02:00:30,504 ERROR apscheduler.executors.default : Job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-01 22:30:00 MSK)" raised an exception
Traceback (most recent call last):
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/roma/Desktop/moodifyspotify/flask_app.py", line 391, in scarp_users_history
    users = mongo_conn.get_all_users()
  File "/Users/roma/Desktop/moodifyspotify/mongo_connector.py", line 46, in get_all_users
    for u in self.dbs.users.find():
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1130, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1935, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1883, in __start_session
    server_session = self._get_server_session()
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1921, in _get_server_session
    return self._topology.get_server_session()
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/topology.py", line 520, in get_server_session
    session_timeout = self._check_session_support()
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/topology.py", line 504, in _check_session_support
    self._select_servers_loop(
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/topology.py", line 218, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: rc1a-zptn64g6pn8ylwgh.mdb.yandexcloud.net:27018: [Errno 61] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 617079cfd660d857bd50c176, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('rc1a-zptn64g6pn8ylwgh.mdb.yandexcloud.net', 27018) server_type: Unknown, rtt: None, error=AutoReconnect('rc1a-zptn64g6pn8ylwgh.mdb.yandexcloud.net:27018: [Errno 61] Connection refused')>]>
2021-11-02 02:30:00,063 INFO apscheduler.executors.default : Running job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-01 23:00:00 MSK)" (scheduled at 2021-11-01 22:30:00+03:00)
2021-11-02 02:30:00,064 INFO apscheduler.executors.default : Running job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-01 23:00:00 MSK)" (scheduled at 2021-11-01 22:30:00+03:00)
2021-11-02 02:30:30,094 ERROR apscheduler.executors.default : Job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-01 23:00:00 MSK)" raised an exception
Traceback (most recent call last):
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/roma/Desktop/moodifyspotify/flask_app.py", line 391, in scarp_users_history
    users = mongo_conn.get_all_users()
  File "/Users/roma/Desktop/moodifyspotify/mongo_connector.py", line 46, in get_all_users
    for u in self.dbs.users.find():
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1130, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1935, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1883, in __start_session
    server_session = self._get_server_session()
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1921, in _get_server_session
    return self._topology.get_server_session()
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/topology.py", line 520, in get_server_session
    session_timeout = self._check_session_support()
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/topology.py", line 504, in _check_session_support
    self._select_servers_loop(
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/topology.py", line 218, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: rc1a-zptn64g6pn8ylwgh.mdb.yandexcloud.net:27018: [Errno 61] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 617079d7ccabbe952692dff8, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('rc1a-zptn64g6pn8ylwgh.mdb.yandexcloud.net', 27018) server_type: Unknown, rtt: None, error=AutoReconnect('rc1a-zptn64g6pn8ylwgh.mdb.yandexcloud.net:27018: [Errno 61] Connection refused')>]>
2021-11-02 02:30:30,095 ERROR apscheduler.executors.default : Job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-01 23:00:00 MSK)" raised an exception
Traceback (most recent call last):
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/roma/Desktop/moodifyspotify/flask_app.py", line 391, in scarp_users_history
    users = mongo_conn.get_all_users()
  File "/Users/roma/Desktop/moodifyspotify/mongo_connector.py", line 46, in get_all_users
    for u in self.dbs.users.find():
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1130, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1935, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1883, in __start_session
    server_session = self._get_server_session()
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1921, in _get_server_session
    return self._topology.get_server_session()
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/topology.py", line 520, in get_server_session
    session_timeout = self._check_session_support()
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/topology.py", line 504, in _check_session_support
    self._select_servers_loop(
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/topology.py", line 218, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: rc1a-zptn64g6pn8ylwgh.mdb.yandexcloud.net:27018: [Errno 61] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 617079cfd660d857bd50c176, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('rc1a-zptn64g6pn8ylwgh.mdb.yandexcloud.net', 27018) server_type: Unknown, rtt: None, error=AutoReconnect('rc1a-zptn64g6pn8ylwgh.mdb.yandexcloud.net:27018: [Errno 61] Connection refused')>]>
2021-11-02 03:00:00,064 INFO apscheduler.executors.default : Running job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-01 23:30:00 MSK)" (scheduled at 2021-11-01 23:00:00+03:00)
2021-11-02 03:00:00,066 INFO apscheduler.executors.default : Running job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-01 23:30:00 MSK)" (scheduled at 2021-11-01 23:00:00+03:00)
2021-11-02 03:00:30,287 ERROR apscheduler.executors.default : Job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-01 23:30:00 MSK)" raised an exception
Traceback (most recent call last):
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/roma/Desktop/moodifyspotify/flask_app.py", line 391, in scarp_users_history
    users = mongo_conn.get_all_users()
  File "/Users/roma/Desktop/moodifyspotify/mongo_connector.py", line 46, in get_all_users
    for u in self.dbs.users.find():
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1130, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1935, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1883, in __start_session
    server_session = self._get_server_session()
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1921, in _get_server_session
    return self._topology.get_server_session()
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/topology.py", line 520, in get_server_session
    session_timeout = self._check_session_support()
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/topology.py", line 504, in _check_session_support
    self._select_servers_loop(
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/topology.py", line 218, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: rc1a-zptn64g6pn8ylwgh.mdb.yandexcloud.net:27018: [Errno 61] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 617079d7ccabbe952692dff8, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('rc1a-zptn64g6pn8ylwgh.mdb.yandexcloud.net', 27018) server_type: Unknown, rtt: None, error=AutoReconnect('rc1a-zptn64g6pn8ylwgh.mdb.yandexcloud.net:27018: [Errno 61] Connection refused')>]>
2021-11-02 03:00:30,287 ERROR apscheduler.executors.default : Job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-01 23:30:00 MSK)" raised an exception
Traceback (most recent call last):
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/roma/Desktop/moodifyspotify/flask_app.py", line 391, in scarp_users_history
    users = mongo_conn.get_all_users()
  File "/Users/roma/Desktop/moodifyspotify/mongo_connector.py", line 46, in get_all_users
    for u in self.dbs.users.find():
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1130, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1935, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1883, in __start_session
    server_session = self._get_server_session()
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1921, in _get_server_session
    return self._topology.get_server_session()
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/topology.py", line 520, in get_server_session
    session_timeout = self._check_session_support()
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/topology.py", line 504, in _check_session_support
    self._select_servers_loop(
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/pymongo/topology.py", line 218, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: rc1a-zptn64g6pn8ylwgh.mdb.yandexcloud.net:27018: [Errno 61] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 617079cfd660d857bd50c176, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('rc1a-zptn64g6pn8ylwgh.mdb.yandexcloud.net', 27018) server_type: Unknown, rtt: None, error=AutoReconnect('rc1a-zptn64g6pn8ylwgh.mdb.yandexcloud.net:27018: [Errno 61] Connection refused')>]>
2021-11-04 20:12:05,947 WARNING apscheduler.executors.default : Run time of job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-04 20:30:00 MSK)" was missed by 0:12:05.946335
2021-11-04 20:12:05,951 WARNING apscheduler.executors.default : Run time of job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-04 20:30:00 MSK)" was missed by 0:12:05.949943
2021-11-11 21:05:32,685 WARNING apscheduler.executors.default : Run time of job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-11 21:30:00 MSK)" was missed by 0:05:32.684358
2021-11-11 21:05:32,685 WARNING apscheduler.executors.default : Run time of job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-11 21:30:00 MSK)" was missed by 0:05:32.685135
2021-11-11 21:30:00,067 INFO apscheduler.executors.default : Running job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-11 22:00:00 MSK)" (scheduled at 2021-11-11 21:30:00+03:00)
2021-11-11 21:30:00,069 INFO apscheduler.executors.default : Running job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-11 22:00:00 MSK)" (scheduled at 2021-11-11 21:30:00+03:00)
2021-11-11 21:30:03,113 INFO apscheduler.executors.default : Job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-11 22:00:00 MSK)" executed successfully
2021-11-11 21:30:03,287 INFO apscheduler.executors.default : Job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-11 22:00:00 MSK)" executed successfully
2021-11-11 22:00:00,039 INFO apscheduler.executors.default : Running job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-11 22:30:00 MSK)" (scheduled at 2021-11-11 22:00:00+03:00)
2021-11-11 22:00:00,040 INFO apscheduler.executors.default : Running job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-11 22:30:00 MSK)" (scheduled at 2021-11-11 22:00:00+03:00)
2021-11-11 22:00:02,543 INFO apscheduler.executors.default : Job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-11 22:30:00 MSK)" executed successfully
2021-11-11 22:00:02,628 INFO apscheduler.executors.default : Job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-11 22:30:00 MSK)" executed successfully
2021-11-13 01:37:57,882 WARNING apscheduler.executors.default : Run time of job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-13 02:00:00 MSK)" was missed by 0:07:57.881066
2021-11-13 01:37:57,882 WARNING apscheduler.executors.default : Run time of job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-13 02:00:00 MSK)" was missed by 0:07:57.881294
2021-11-13 14:37:58,255 WARNING apscheduler.executors.default : Run time of job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-13 15:00:00 MSK)" was missed by 0:07:58.253333
2021-11-13 14:37:58,255 WARNING apscheduler.executors.default : Run time of job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-13 15:00:00 MSK)" was missed by 0:07:58.253637
2021-11-13 14:53:23,778 INFO apscheduler.scheduler : Scheduler started
2021-11-13 14:53:23,902 INFO apscheduler.scheduler : Added job "create_app.<locals>.scarp_users_history" to job store "default"
2021-11-13 14:53:23,913 WARNING werkzeug :  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-11-13 14:53:23,913 INFO werkzeug :  * Running on http://172.20.10.3:5000/ (Press CTRL+C to quit)
2021-11-13 14:53:23,915 INFO werkzeug :  * Restarting with stat
2021-11-13 14:53:30,559 INFO apscheduler.scheduler : Scheduler started
2021-11-13 14:53:30,699 INFO apscheduler.scheduler : Added job "create_app.<locals>.scarp_users_history" to job store "default"
2021-11-13 14:53:30,711 WARNING werkzeug :  * Debugger is active!
2021-11-13 14:53:30,731 INFO werkzeug :  * Debugger PIN: 142-798-951
2021-11-13 14:54:31,339 INFO apscheduler.scheduler : Scheduler started
2021-11-13 14:54:31,663 INFO apscheduler.scheduler : Added job "create_app.<locals>.scarp_users_history" to job store "default"
2021-11-13 14:54:31,689 WARNING werkzeug :  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-11-13 14:54:31,689 INFO werkzeug :  * Running on http://172.20.10.3:5000/ (Press CTRL+C to quit)
2021-11-13 14:54:31,692 INFO werkzeug :  * Restarting with stat
2021-11-13 14:54:42,247 INFO apscheduler.scheduler : Scheduler started
2021-11-13 14:54:42,539 INFO apscheduler.scheduler : Added job "create_app.<locals>.scarp_users_history" to job store "default"
2021-11-13 14:54:42,564 WARNING werkzeug :  * Debugger is active!
2021-11-13 14:54:42,578 INFO werkzeug :  * Debugger PIN: 142-798-951
2021-11-13 14:56:54,602 INFO werkzeug : 172.20.10.3 - - [13/Nov/2021 14:56:54] "GET / HTTP/1.1" 200 -
2021-11-13 14:56:54,664 INFO werkzeug : 172.20.10.3 - - [13/Nov/2021 14:56:54] "GET /static/style.css HTTP/1.1" 200 -
2021-11-13 14:56:54,667 INFO werkzeug : 172.20.10.3 - - [13/Nov/2021 14:56:54] "[36mGET /static/logo2.svg HTTP/1.1[0m" 304 -
2021-11-13 14:57:15,510 INFO werkzeug :  * Detected change in '/Users/roma/Desktop/moodifyspotify/flask_app.py', reloading
2021-11-13 14:57:16,568 INFO werkzeug :  * Restarting with stat
2021-11-13 14:57:37,937 INFO apscheduler.scheduler : Scheduler started
2021-11-13 14:57:38,197 INFO apscheduler.scheduler : Added job "create_app.<locals>.scarp_users_history" to job store "default"
2021-11-13 14:57:38,214 WARNING werkzeug :  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-11-13 14:57:38,215 INFO werkzeug :  * Running on http://172.20.10.3:5000/ (Press CTRL+C to quit)
2021-11-13 14:57:38,217 INFO werkzeug :  * Restarting with stat
2021-11-13 14:57:52,492 INFO apscheduler.scheduler : Scheduler started
2021-11-13 14:57:52,952 INFO apscheduler.scheduler : Added job "create_app.<locals>.scarp_users_history" to job store "default"
2021-11-13 14:57:52,972 WARNING werkzeug :  * Debugger is active!
2021-11-13 14:57:52,987 INFO werkzeug :  * Debugger PIN: 142-798-951
2021-11-13 14:59:18,556 INFO werkzeug : 172.20.10.3 - - [13/Nov/2021 14:59:18] "GET / HTTP/1.1" 200 -
2021-11-13 14:59:18,637 INFO werkzeug : 172.20.10.3 - - [13/Nov/2021 14:59:18] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
2021-11-13 14:59:18,643 INFO werkzeug : 172.20.10.3 - - [13/Nov/2021 14:59:18] "[36mGET /static/logo2.svg HTTP/1.1[0m" 304 -
2021-11-13 14:59:27,138 INFO werkzeug : 172.20.10.3 - - [13/Nov/2021 14:59:27] "[32mGET /spotify_auth?code=AQBDlvuoLSdgEFyX7-wqG8eAFqyCLiMCHIWwU1r3Z8xVMvz9JCHOBcpqc2aeVUmnf9JSMHDZzHaRLALOM4coDNUxJhWfX0QTU3TRWf4REI3Y3_4Nq_4qk8szV8AcgxWdJYM__rQ_K5xljTCXuWOQoS-3t-vjViaCMdh3qiavot0OosPcAStAgNY9kJznwE9OIUi5U0cyYUVSOv63xvwx3ieL4jsmblKl0oUaTR7DE65V4INCj7D0bITLBuFyxw2ecJzSydRynNfs6_fg5j_fN8CuCfNGQ5ZS5YdicW8Ig3goSYtvlV05exog6gDAoJvVfdEGTUesCg HTTP/1.1[0m" 302 -
2021-11-13 15:00:00,007 INFO apscheduler.executors.default : Running job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-13 15:00:00 MSK)" (scheduled at 2021-11-13 15:00:00+03:00)
2021-11-13 15:00:00,015 INFO apscheduler.executors.default : Running job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-13 15:00:00 MSK)" (scheduled at 2021-11-13 15:00:00+03:00)
2021-11-13 15:00:04,780 INFO apscheduler.executors.default : Job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-13 15:30:00 MSK)" executed successfully
2021-11-13 15:00:04,792 INFO apscheduler.executors.default : Job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-13 15:30:00 MSK)" executed successfully
2021-11-13 15:00:56,682 INFO apscheduler.scheduler : Scheduler started
2021-11-13 15:00:56,978 INFO apscheduler.scheduler : Added job "create_app.<locals>.scarp_users_history" to job store "default"
2021-11-13 15:00:57,002 WARNING werkzeug :  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-11-13 15:00:57,002 INFO werkzeug :  * Running on http://172.20.10.3:5000/ (Press CTRL+C to quit)
2021-11-13 15:00:57,005 INFO werkzeug :  * Restarting with stat
2021-11-13 15:01:07,168 INFO apscheduler.scheduler : Scheduler started
2021-11-13 15:01:07,468 INFO apscheduler.scheduler : Added job "create_app.<locals>.scarp_users_history" to job store "default"
2021-11-13 15:01:07,496 WARNING werkzeug :  * Debugger is active!
2021-11-13 15:01:07,514 INFO werkzeug :  * Debugger PIN: 142-798-951
2021-11-13 15:30:00,192 INFO apscheduler.executors.default : Running job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-13 16:00:00 MSK)" (scheduled at 2021-11-13 15:30:00+03:00)
2021-11-13 15:30:00,292 INFO apscheduler.executors.default : Running job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-13 16:00:00 MSK)" (scheduled at 2021-11-13 15:30:00+03:00)
2021-11-13 15:30:02,814 ERROR apscheduler.executors.default : Job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-13 16:00:00 MSK)" raised an exception
Traceback (most recent call last):
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/roma/Desktop/moodifyspotify/flask_app.py", line 396, in scarp_users_history
    tracks_history = sp_user_clt.get_user_recent_tracks()
  File "/Users/roma/Desktop/moodifyspotify/spotify_client.py", line 124, in get_user_recent_tracks
    for lu in resp['items']:
KeyError: 'items'
2021-11-13 15:30:02,824 ERROR apscheduler.executors.default : Job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-13 16:00:00 MSK)" raised an exception
Traceback (most recent call last):
  File "/Users/roma/Desktop/moodifyspotify/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/roma/Desktop/moodifyspotify/flask_app.py", line 396, in scarp_users_history
    tracks_history = sp_user_clt.get_user_recent_tracks()
  File "/Users/roma/Desktop/moodifyspotify/spotify_client.py", line 124, in get_user_recent_tracks
    for lu in resp['items']:
KeyError: 'items'
2021-11-14 14:48:55,103 WARNING apscheduler.executors.default : Run time of job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-14 15:00:00 MSK)" was missed by 0:18:55.102599
2021-11-14 14:48:55,172 WARNING apscheduler.executors.default : Run time of job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-14 15:00:00 MSK)" was missed by 0:18:55.171441
2021-11-14 15:00:00,007 INFO apscheduler.executors.default : Running job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-14 15:30:00 MSK)" (scheduled at 2021-11-14 15:00:00+03:00)
2021-11-14 15:00:00,008 INFO apscheduler.executors.default : Running job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-14 15:30:00 MSK)" (scheduled at 2021-11-14 15:00:00+03:00)
2021-11-14 15:00:17,836 INFO apscheduler.executors.default : Job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-14 15:30:00 MSK)" executed successfully
2021-11-14 15:00:17,948 INFO apscheduler.executors.default : Job "create_app.<locals>.scarp_users_history (trigger: cron[minute='*/30', second='0'], next run at: 2021-11-14 15:30:00 MSK)" executed successfully
2021-11-14 15:02:47,415 INFO werkzeug :  * Detected change in '/Users/roma/Desktop/moodifyspotify/mongo_connector.py', reloading
2021-11-14 15:02:49,547 INFO werkzeug :  * Restarting with stat
2021-11-14 16:03:04,734 INFO apscheduler.scheduler : Scheduler started
2021-11-14 16:03:04,854 INFO apscheduler.scheduler : Added job "create_app.<locals>.scarp_users_history" to job store "default"
2021-11-14 16:03:04,864 WARNING werkzeug :  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-11-14 16:03:04,864 INFO werkzeug :  * Running on http://172.20.10.3:5000/ (Press CTRL+C to quit)
2021-11-14 16:03:04,866 INFO werkzeug :  * Restarting with stat
2021-11-14 16:03:11,212 INFO apscheduler.scheduler : Scheduler started
2021-11-14 16:03:11,298 INFO apscheduler.scheduler : Added job "create_app.<locals>.scarp_users_history" to job store "default"
2021-11-14 16:03:11,307 WARNING werkzeug :  * Debugger is active!
2021-11-14 16:03:11,329 INFO werkzeug :  * Debugger PIN: 142-798-951
2021-11-14 17:50:51,907 INFO apscheduler.scheduler : Scheduler started
2021-11-14 17:50:51,957 WARNING werkzeug :  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-11-14 17:50:51,958 INFO werkzeug :  * Running on http://172.20.10.3:5000/ (Press CTRL+C to quit)
2021-11-14 17:50:51,959 INFO werkzeug :  * Restarting with stat
2021-11-14 17:50:57,215 INFO apscheduler.scheduler : Scheduler started
2021-11-14 17:50:57,263 WARNING werkzeug :  * Debugger is active!
2021-11-14 17:50:57,288 INFO werkzeug :  * Debugger PIN: 142-798-951
2021-11-14 17:51:28,798 INFO werkzeug : 172.20.10.3 - - [14/Nov/2021 17:51:28] "GET / HTTP/1.1" 200 -
2021-11-14 17:51:28,919 INFO werkzeug : 172.20.10.3 - - [14/Nov/2021 17:51:28] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
2021-11-14 17:51:29,290 INFO werkzeug : 172.20.10.3 - - [14/Nov/2021 17:51:29] "[36mGET /static/logo2.svg HTTP/1.1[0m" 304 -
2021-11-14 17:51:47,401 INFO werkzeug : 172.20.10.3 - - [14/Nov/2021 17:51:47] "[35m[1mGET /run_history_calc HTTP/1.1[0m" 500 -
2021-11-14 17:51:47,477 INFO werkzeug : 172.20.10.3 - - [14/Nov/2021 17:51:47] "GET /run_history_calc?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
2021-11-14 17:51:47,486 INFO werkzeug : 172.20.10.3 - - [14/Nov/2021 17:51:47] "GET /run_history_calc?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
2021-11-14 17:51:47,525 INFO werkzeug : 172.20.10.3 - - [14/Nov/2021 17:51:47] "GET /run_history_calc?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2021-11-14 17:51:47,783 INFO werkzeug : 172.20.10.3 - - [14/Nov/2021 17:51:47] "GET /run_history_calc?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
2021-11-14 17:51:47,820 INFO werkzeug : 172.20.10.3 - - [14/Nov/2021 17:51:47] "GET /run_history_calc?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2021-11-14 17:53:29,275 INFO werkzeug :  * Detected change in '/Users/roma/Desktop/moodifyspotify/mongo_connector.py', reloading
2021-11-14 17:53:30,530 INFO werkzeug :  * Restarting with stat
2021-11-14 17:53:38,551 INFO apscheduler.scheduler : Scheduler started
2021-11-14 17:53:38,611 WARNING werkzeug :  * Debugger is active!
2021-11-14 17:53:38,627 INFO werkzeug :  * Debugger PIN: 142-798-951
2021-11-14 17:55:54,228 INFO apscheduler.scheduler : Scheduler started
2021-11-14 17:55:54,279 WARNING werkzeug :  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-11-14 17:55:54,279 INFO werkzeug :  * Running on http://172.20.10.3:5000/ (Press CTRL+C to quit)
2021-11-14 17:55:54,281 INFO werkzeug :  * Restarting with stat
2021-11-14 17:55:59,351 INFO apscheduler.scheduler : Scheduler started
2021-11-14 17:55:59,389 WARNING werkzeug :  * Debugger is active!
2021-11-14 17:55:59,403 INFO werkzeug :  * Debugger PIN: 142-798-951
2021-11-14 17:56:27,341 INFO werkzeug : 172.20.10.3 - - [14/Nov/2021 17:56:27] "[35m[1mGET /run_history_calc HTTP/1.1[0m" 500 -
2021-11-14 17:56:27,419 INFO werkzeug : 172.20.10.3 - - [14/Nov/2021 17:56:27] "GET /run_history_calc?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
2021-11-14 17:56:27,421 INFO werkzeug : 172.20.10.3 - - [14/Nov/2021 17:56:27] "GET /run_history_calc?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
2021-11-14 17:56:27,493 INFO werkzeug : 172.20.10.3 - - [14/Nov/2021 17:56:27] "GET /run_history_calc?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2021-11-14 17:56:27,895 INFO werkzeug : 172.20.10.3 - - [14/Nov/2021 17:56:27] "GET /run_history_calc?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
2021-11-14 17:56:27,939 INFO werkzeug : 172.20.10.3 - - [14/Nov/2021 17:56:27] "GET /run_history_calc?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2021-11-14 17:57:43,099 INFO apscheduler.scheduler : Scheduler started
2021-11-14 17:57:43,311 WARNING werkzeug :  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-11-14 17:57:43,311 INFO werkzeug :  * Running on http://172.20.10.3:5000/ (Press CTRL+C to quit)
2021-11-14 17:57:43,313 INFO werkzeug :  * Restarting with stat
2021-11-14 17:57:51,988 INFO apscheduler.scheduler : Scheduler started
2021-11-14 17:57:52,081 WARNING werkzeug :  * Debugger is active!
2021-11-14 17:57:52,100 INFO werkzeug :  * Debugger PIN: 142-798-951
2021-11-14 18:00:53,625 INFO apscheduler.scheduler : Scheduler started
2021-11-14 18:00:53,676 WARNING werkzeug :  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-11-14 18:00:53,676 INFO werkzeug :  * Running on http://172.20.10.3:5000/ (Press CTRL+C to quit)
2021-11-14 18:00:53,678 INFO werkzeug :  * Restarting with stat
2021-11-14 18:00:59,022 INFO apscheduler.scheduler : Scheduler started
2021-11-14 18:00:59,063 WARNING werkzeug :  * Debugger is active!
2021-11-14 18:00:59,072 INFO werkzeug :  * Debugger PIN: 142-798-951
2021-11-14 18:01:11,736 INFO werkzeug : 172.20.10.3 - - [14/Nov/2021 18:01:11] "[35m[1mGET /run_history_calc HTTP/1.1[0m" 500 -
2021-11-14 18:01:11,799 INFO werkzeug : 172.20.10.3 - - [14/Nov/2021 18:01:11] "GET /run_history_calc?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
2021-11-14 18:01:11,807 INFO werkzeug : 172.20.10.3 - - [14/Nov/2021 18:01:11] "GET /run_history_calc?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
2021-11-14 18:01:11,875 INFO werkzeug : 172.20.10.3 - - [14/Nov/2021 18:01:11] "GET /run_history_calc?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2021-11-14 18:01:12,036 INFO werkzeug : 172.20.10.3 - - [14/Nov/2021 18:01:12] "GET /run_history_calc?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
2021-11-14 18:01:12,356 INFO werkzeug : 172.20.10.3 - - [14/Nov/2021 18:01:12] "GET /run_history_calc?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2021-11-14 18:02:08,994 INFO werkzeug :  * Detected change in '/Users/roma/Desktop/moodifyspotify/flask_app.py', reloading
2021-11-14 18:02:09,957 INFO werkzeug :  * Restarting with stat
2021-11-14 18:02:15,971 INFO apscheduler.scheduler : Scheduler started
2021-11-14 18:02:16,018 WARNING werkzeug :  * Debugger is active!
2021-11-14 18:02:16,029 INFO werkzeug :  * Debugger PIN: 142-798-951
2021-11-14 18:03:53,295 INFO werkzeug :  * Detected change in '/Users/roma/Desktop/moodifyspotify/flask_app.py', reloading
2021-11-14 18:03:54,163 INFO werkzeug :  * Restarting with stat
